spring:
  config:
    activate:
      on-profile: prod

  application:
    name: rag-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/rag
    username: root
    password: ${DB-PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  ai:
    openai:
      api-key: ${OPENAI-API-KEY}
      chat:
        options:
          model: gpt-5-mini
          max_completion_tokens: 12000
          temperature: 1

eureka:
  client:
    enabled: false
